#!/bin/bash
#------------------------------------------------------------------------------#
#DESCRIPTION=Script for handle p7m files
#AUTHOR=Lucio Pasquini, Alessio Tomelleri
#MAIL=lpasquini@arpa.veneto.it
#DATE=08/02/2015
#VERSION=0.1
#------------------------------------------------------------------------------#

FILE="$(zenity --file-selection --title="Seleziona il file")"

case $? in
        0)
            FILENAME=$(basename "$FILE")
            openssl smime -verify -inform DER -in "$FILE" -noverify -out ~/"${FILENAME%.*}"
            xdg-open ~/"${FILENAME%.*}";;
        1)
            zenity --error --text="Nessun file selezionato !";;
        -1)
            zenity --error --text="Errore inatteso !";;
esac
