#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/somethingnotexist -a -d /usr/share/doc/somethingnotexist ]; then
    ln -sf ../share/doc/somethingnotexist /usr/doc/somethingnotexist
  fi
fi
# End automatically added section
